app: 
    name: my app
    description: Welcome to ${app.name}

my:
    greeting: Hello how are u
    list:
        values: one,two,three

dbValues: "{connectionString: 'http://__', userName: 'test', password: 'password'}"

db:
    connection: ${dbValues}
    host: 127.0.0.1
    port: 1200

management.endpoints.web.exposure.include: "*"

spring.profiles.active: test
